package com.webservice.ubicaplus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2022-10-06T16:07:11.708+06:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "UbicaPlusWSService",
                  wsdlLocation = "file:/D:/utilities/spring-mvc-rest/src/main/resources/wsdl/UbicaPlus.wsdl",
                  targetNamespace = "http://ubicaplus.webservice.com")
public class UbicaPlusWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ubicaplus.webservice.com", "UbicaPlusWSService");
    public final static QName UbicaPlus = new QName("http://ubicaplus.webservice.com", "UbicaPlus");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/utilities/spring-mvc-rest/src/main/resources/wsdl/UbicaPlus.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UbicaPlusWSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/utilities/spring-mvc-rest/src/main/resources/wsdl/UbicaPlus.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UbicaPlusWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UbicaPlusWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UbicaPlusWSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UbicaPlusWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UbicaPlusWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UbicaPlusWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UbicaPlusWS
     */
    @WebEndpoint(name = "UbicaPlus")
    public UbicaPlusWS getUbicaPlus() {
        return super.getPort(UbicaPlus, UbicaPlusWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UbicaPlusWS
     */
    @WebEndpoint(name = "UbicaPlus")
    public UbicaPlusWS getUbicaPlus(WebServiceFeature... features) {
        return super.getPort(UbicaPlus, UbicaPlusWS.class, features);
    }

}
